# Generated by Django 5.2.11 on 2026-02-26 06:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('sentiment', models.CharField(choices=[('positive', '긍정'), ('neutral', '중립'), ('negative', '부정')], default='neutral', max_length=10, verbose_name='감정')),
                ('sentiment_score', models.FloatField(default=0.0, verbose_name='감정 점수')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='키워드')),
                ('year_month', models.CharField(help_text='예: 2025-02', max_length=7, verbose_name='연월')),
                ('review_date', models.DateField(verbose_name='리뷰 날짜')),
                ('source', models.CharField(default='yogiyo', max_length=50, verbose_name='출처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='MenuReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentioned_text', models.TextField(blank=True, verbose_name='언급 텍스트')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_reviews', to='stores.menu')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_reviews', to='reviews.review')),
            ],
            options={
                'verbose_name': '메뉴 리뷰',
                'verbose_name_plural': '메뉴 리뷰',
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, verbose_name='연월')),
                ('summary', models.TextField(blank=True, verbose_name='AI 요약')),
                ('highlights', models.JSONField(blank=True, default=dict, verbose_name='하이라이트')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='월 평균 평점')),
                ('review_count', models.IntegerField(default=0, verbose_name='월 리뷰 수')),
                ('sentiment_distribution', models.JSONField(blank=True, default=dict, help_text='예: {"positive": 60, "neutral": 25, "negative": 15}', verbose_name='감정 분포')),
                ('top_keywords', models.JSONField(blank=True, default=list, verbose_name='상위 키워드')),
                ('rating_change', models.FloatField(default=0.0, verbose_name='평점 변화')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='생성일시')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='stores.store')),
            ],
            options={
                'verbose_name': '월별 요약',
                'verbose_name_plural': '월별 요약',
                'ordering': ['-year_month'],
                'unique_together': {('store', 'year_month')},
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['store', 'year_month'], name='idx_store_year_month'),
        ),
    ]
