# Generated by Django 5.2.11 on 2026-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_images'),
        ('stores', '0002_menu_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklysummary',
            options={'ordering': ['-week'], 'verbose_name': '주별 요약', 'verbose_name_plural': '주별 요약'},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='idx_store_year_month',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='idx_store_year_week',
        ),
        migrations.RemoveField(
            model_name='review',
            name='year_month',
        ),
        migrations.RemoveField(
            model_name='review',
            name='year_week',
        ),
        migrations.AddField(
            model_name='review',
            name='week',
            field=models.IntegerField(default=0, help_text='예: 14 (ISO 주차)', verbose_name='주차'),
        ),
        # WeeklySummary: week 추가 먼저, unique_together 변경 후, year_week 제거
        migrations.AddField(
            model_name='weeklysummary',
            name='week',
            field=models.IntegerField(default=0, verbose_name='주차'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysummary',
            unique_together={('store', 'week')},
        ),
        migrations.RemoveField(
            model_name='weeklysummary',
            name='year_week',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['store', 'week', 'created_at'], name='idx_store_week_created'),
        ),
    ]
