# Generated by Django 5.2.11 on 2026-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_weeklysummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='blinded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='블라인드일시'),
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_blinded',
            field=models.BooleanField(default=False, verbose_name='블라인드 여부'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
    ]
