# Generated by Django 5.2.11 on 2026-02-26 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='가게명')),
                ('category', models.CharField(choices=[('korean', '한식'), ('japanese', '일식'), ('chinese', '중식'), ('western', '양식'), ('chicken', '치킨'), ('pizza', '피자'), ('cafe', '카페'), ('etc', '기타')], max_length=20, verbose_name='카테고리')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='평균 평점')),
                ('total_review_count', models.IntegerField(default=0, verbose_name='총 리뷰 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='메뉴 카테고리')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='stores.store')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
            },
        ),
    ]
