# Generated by Django 5.2.11 on 2026-04-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_rename_shopweeksentimentreveiw_to_shopweekreviewsentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '실행 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('triggered_by', models.CharField(choices=[('schedule', '스케줄'), ('manual', '수동')], default='schedule', max_length=20, verbose_name='트리거')),
                ('raw_response', models.TextField(blank=True, verbose_name='LLM 원본 응답')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('source_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='stores.shopweekreview', verbose_name='기준 주차')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='stores.store', verbose_name='가게')),
            ],
            options={
                'verbose_name': 'AI 분석 작업',
                'verbose_name_plural': 'AI 분석 작업',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('action_detail', models.TextField(verbose_name='구체적 조치')),
                ('level', models.CharField(choices=[('danger', '위험'), ('warning', '주의'), ('info', '정보'), ('success', '긍정')], default='info', max_length=20, verbose_name='레벨')),
                ('priority', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=20, verbose_name='우선순위')),
                ('status', models.CharField(choices=[('open', '미처리'), ('in_progress', '처리 중'), ('completed', '완료'), ('dismissed', '기각')], default='open', max_length=20, verbose_name='상태')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('completed_note', models.TextField(blank=True, verbose_name='완료 메모')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='관련 링크 URL')),
                ('link_label', models.CharField(blank=True, max_length=100, verbose_name='관련 링크 텍스트')),
                ('week_year', models.IntegerField(verbose_name='집계 연도')),
                ('week_number', models.IntegerField(verbose_name='집계 주차')),
                ('is_ai_generated', models.BooleanField(default=True, verbose_name='AI 생성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='stores.store', verbose_name='가게')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='stores.aianalysisjob', verbose_name='출처 작업')),
            ],
            options={
                'verbose_name': 'AI 액션 아이템',
                'verbose_name_plural': 'AI 액션 아이템',
                'ordering': [models.Case(models.When(priority='high', then=0), models.When(priority='medium', then=1), models.When(priority='low', then=2), default=3, output_field=models.IntegerField()), '-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='idx_action_store_status')],
            },
        ),
    ]
