# Generated by Django 5.2.11 on 2026-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_aianalysisjob_aiactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiactionitem',
            name='item_type',
            field=models.CharField(choices=[('action', '개선 할일'), ('strength', '강점 인사이트')], default='action', max_length=20, verbose_name='아이템 유형'),
        ),
        migrations.AlterField(
            model_name='aiactionitem',
            name='status',
            field=models.CharField(choices=[('open', '미처리'), ('in_progress', '처리 중'), ('completed', '완료'), ('dismissed', '기각'), ('confirmed', '확인됨')], default='open', max_length=20, verbose_name='상태'),
        ),
    ]
